### ISSUE TITLE
Scrum update 2

### ISSUE THREAD

**Issue by baconandchips** [CourseFlo/Flo#4]
- This week, I added React-Router to our projects to allow multiple page displays for our current stage of prototyping. I have also created numerous components in order to support the fourth-page view of courses, and have set up minor groundwork for the course display in the future.
- One roadblock I have hit in this milestone is time management, as my started internship made my schedule a bit more compact than usual. Combined with my late personal assignment, time management has been a bit on the slippery side this week.
- In the coming weeks, I hope to be integrating Redux in the app with my teammates; I believe that Sepand has made good progress on this front. Anyways, I hope to be fleshing out more components and standardizing our formats. This may involve more learning on the Material-UI framework. 

CSID: n0k0b

**Comment by DSep** [comment]
- On my part, I spent more time learning React (especially larger scale functional component use) and Material UI to implement into the project. I produced my course browse/search page's initial state, with some Redux already integrate since it made interacting with the page nicer.
- The Redux state control on the page became bugged near the deadline, and I struggled to find a way to fix it before the deadline. I was able to fix it after the deadline, but as this is also a milestone for next week, it wasn't too major of an issue.
- For the first half of the sprint, I will be focussing on the cleanup of the existing course browsing code, as well as adding functionality to bring it to a complete page within the app. Within our tasks, I am working on creating an abstraction system for pages vs components, and refactoring my current code to fit into that paradigm. I am also going to help with others working on their material UI work, help with reduxification of other's pages, helping with others' transition to a page-component paradigm, and globalizing styles. There will be additional tasks in the second half of the sprint, since we are pushing to bring the UI to completion.

CSID: g3u1b

**Comment by yqj2k** [comment]
- I worked on the home page, after the user logs in. I utilized many material UI components to make the home page (Box, List, Grid, Card...) and created a mockup of links and a form that users can make to customize their profile before approaching the course search part of our application.
- One issue I had through this sprint was not being clear in what I would be doing with my implementation. Lack of communication resulted in me falling back to my mock-up, which meets the criteria but not my expectations.
- After the design reviews, I realize there is a lot I can work on to achieve the design we want for our application. On top of finishing off the design for our application, I intend to include redux actions that store the courses that a user is selecting and store their profile information. More actions may be included, but a goal for me is to implement the full workflow a user would do through our application.
CSID: a4g2b

**Comment by beetai** [comment]
- I worked on setting up React and Redux and setting up the project for development for this milestone, as well as helped with some code reviews. I also worked on the login page for our app. 
- I felt like a large struggle was certainly not being very clear on all the details and how to approach such a large project, and finding the right place to start. Additionally, time management has been difficult and a lack of it has caused me to fall behind.
- I am planning to work on a homepage and a navbar that we will all be able to use. Additionally, I need to learn how to use Material UI. I also hope to help our team integrate globalized styling within our project.

CSID: c8m1b
